server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /mumu-oa

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mumu-oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: aaaa1234
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: aaaa1234
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mumu-oa
      authentication-database: oa-db
      username: admin
      password: aaaa1234

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.mumuoa.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.mumuoa.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"

mumuoa:
  jwt:
    #密钥
    secret: abc123456
    #过期时间,单位为天
    expire: 5
    #redis缓存过期时间，单位为天
    cache-expire: 10

wx:
  app-id:
  app-secret: